DROP TABLE IF EXISTS wishlists CASCADE;
-- CREATE WISHLISTS
CREATE TABLE wishlists (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE NOT NULL
);