DROP TABLE IF EXISTS items  CASCADE;
-- CREATE ITEMS 
CREATE TABLE items (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  url VARCHAR(255) NOT NULL,
  image VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL,
  wishlist_id INTEGER NOT NULL REFERENCES wishlists(id) ON DELETE CASCADE NOT NULL
);